#!/usr/bin/env bash

work=$1
((work=work?work:1500))
break=$2
((break=break?break:300))
ss=$3
((ss=ss?ss*2:6))
s=( "work" "break" )

for ((i=0;i<ss;i++)){
	timer "${!s[c]}s"

	((c=c?0:1,ct=c?ct:ct++))
	read -rsp "${s[c]} done"
}

