#!/usr/bin/env bash

main(){
	for ((i=0;;i++)){
		timer "${!s[c]}"
		((i>=ss)) && break
		read -rsp $'\e[1;34m\r\e[A\e[K'"${s[c]} done"$'\e[J'
		((c=c?0:1,ct=c?ct:ct++))
	}
}

while getopts ':w:b:s:' o; do
	case $o in
		w) work=$OPTARG; s+=(work) ;;
		b) break=$OPTARG; s+=(break) ;;
		s) ss=$OPTARG ;;
	esac
done
main

