#!/usr/bin/env bash

while getopts ':w:b:s:' o
do case $o in
	w) work="$OPTARG"; s+=(work) ;;
	b) break="$OPTARG"; s+=(break) ;;
	s) ss=$OPTARG ;;
esac; done

for ((c=0,i=0;i<ss*2-1;c=c?0:1,i++)); do
	printf '\n\e[1;3'$((c+3))'m\r\e[1A\e[J%s\n' "${s[c]} $((i/2+1))"
	timer "${!s[c]}"
	read -rsp $'\e[1;3'$((c+3))$'m\r\e[A\e[J'"${s[c]} over, press enter to start ${s[((c?0:1))]}"$'\n'
done
